# Generated by Django 5.2.3 on 2025-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extra_question',
            field=models.TextField(blank=True, verbose_name='Extra Question'),
        ),
    ]
