# Generated by Django 5.2.3 on 2025-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_application_extra_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yashash joyi'),
        ),
    ]
