# Generated by Django 5.2.3 on 2025-06-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='VacancyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_uz', models.CharField(max_length=200)),
                ('label_ru', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('file', 'File Upload'), ('choice', 'Multiple Choice')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.TextField(blank=True, help_text='For multiple choice fields, enter choices one per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='bot.vacancy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
